// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motion.proto

#ifndef PROTOBUF_motion_2eproto__INCLUDED
#define PROTOBUF_motion_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace motion {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_motion_2eproto();
void protobuf_AssignDesc_motion_2eproto();
void protobuf_ShutdownFile_motion_2eproto();

class Message;

enum Message_ActionType {
  Message_ActionType_CONNECT = 1000,
  Message_ActionType_STOP_STREAMING = 1002,
  Message_ActionType_PAUSE_STREAMING = 1003,
  Message_ActionType_START_RECOGNITION = 1004,
  Message_ActionType_STOP_RECOGNITION = 1005,
  Message_ActionType_DISSCONNECT = 1006,
  Message_ActionType_GET_TIME = 1007,
  Message_ActionType_SET_TIME = 1008,
  Message_ActionType_TIME_SET = 1009,
  Message_ActionType_AMOUNT_DETECTED = 1010,
  Message_ActionType_FILE_RECOGNIZED = 1011,
  Message_ActionType_GET_MAT = 1012,
  Message_ActionType_SET_MAT = 1013,
  Message_ActionType_TCP_ECHO_PORT = 5010,
  Message_ActionType_UDP_PORT = 5020,
  Message_ActionType_STREAMING_VIDEO_PORT = 5030,
  Message_ActionType_TCP_MSG_PORT = 5040
};
bool Message_ActionType_IsValid(int value);
const Message_ActionType Message_ActionType_ActionType_MIN = Message_ActionType_CONNECT;
const Message_ActionType Message_ActionType_ActionType_MAX = Message_ActionType_TCP_MSG_PORT;
const int Message_ActionType_ActionType_ARRAYSIZE = Message_ActionType_ActionType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Message_ActionType_descriptor();
inline const ::std::string& Message_ActionType_Name(Message_ActionType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Message_ActionType_descriptor(), value);
}
inline bool Message_ActionType_Parse(
    const ::std::string& name, Message_ActionType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Message_ActionType>(
    Message_ActionType_descriptor(), name, value);
}
// ===================================================================

class Message : public ::google::protobuf::Message {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  Message* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Message_ActionType ActionType;
  static const ActionType CONNECT = Message_ActionType_CONNECT;
  static const ActionType STOP_STREAMING = Message_ActionType_STOP_STREAMING;
  static const ActionType PAUSE_STREAMING = Message_ActionType_PAUSE_STREAMING;
  static const ActionType START_RECOGNITION = Message_ActionType_START_RECOGNITION;
  static const ActionType STOP_RECOGNITION = Message_ActionType_STOP_RECOGNITION;
  static const ActionType DISSCONNECT = Message_ActionType_DISSCONNECT;
  static const ActionType GET_TIME = Message_ActionType_GET_TIME;
  static const ActionType SET_TIME = Message_ActionType_SET_TIME;
  static const ActionType TIME_SET = Message_ActionType_TIME_SET;
  static const ActionType AMOUNT_DETECTED = Message_ActionType_AMOUNT_DETECTED;
  static const ActionType FILE_RECOGNIZED = Message_ActionType_FILE_RECOGNIZED;
  static const ActionType GET_MAT = Message_ActionType_GET_MAT;
  static const ActionType SET_MAT = Message_ActionType_SET_MAT;
  static const ActionType TCP_ECHO_PORT = Message_ActionType_TCP_ECHO_PORT;
  static const ActionType UDP_PORT = Message_ActionType_UDP_PORT;
  static const ActionType STREAMING_VIDEO_PORT = Message_ActionType_STREAMING_VIDEO_PORT;
  static const ActionType TCP_MSG_PORT = Message_ActionType_TCP_MSG_PORT;
  static inline bool ActionType_IsValid(int value) {
    return Message_ActionType_IsValid(value);
  }
  static const ActionType ActionType_MIN =
    Message_ActionType_ActionType_MIN;
  static const ActionType ActionType_MAX =
    Message_ActionType_ActionType_MAX;
  static const int ActionType_ARRAYSIZE =
    Message_ActionType_ActionType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ActionType_descriptor() {
    return Message_ActionType_descriptor();
  }
  static inline const ::std::string& ActionType_Name(ActionType value) {
    return Message_ActionType_Name(value);
  }
  static inline bool ActionType_Parse(const ::std::string& name,
      ActionType* value) {
    return Message_ActionType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .motion.Message.ActionType type = 1 [default = CONNECT];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::motion::Message_ActionType type() const;
  inline void set_type(::motion::Message_ActionType value);

  // optional string time = 2;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 2;
  inline const ::std::string& time() const;
  inline void set_time(const ::std::string& value);
  inline void set_time(const char* value);
  inline void set_time(const char* value, size_t size);
  inline ::std::string* mutable_time();
  inline ::std::string* release_time();
  inline void set_allocated_time(::std::string* time);

  // optional int32 width = 3;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 3;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);

  // optional int32 height = 4;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 4;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);

  // optional int32 rows = 5;
  inline bool has_rows() const;
  inline void clear_rows();
  static const int kRowsFieldNumber = 5;
  inline ::google::protobuf::int32 rows() const;
  inline void set_rows(::google::protobuf::int32 value);

  // optional int32 cols = 6;
  inline bool has_cols() const;
  inline void clear_cols();
  static const int kColsFieldNumber = 6;
  inline ::google::protobuf::int32 cols() const;
  inline void set_cols(::google::protobuf::int32 value);

  // optional int32 typemat = 7;
  inline bool has_typemat() const;
  inline void clear_typemat();
  static const int kTypematFieldNumber = 7;
  inline ::google::protobuf::int32 typemat() const;
  inline void set_typemat(::google::protobuf::int32 value);

  // optional int32 size = 8;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 8;
  inline ::google::protobuf::int32 size() const;
  inline void set_size(::google::protobuf::int32 value);

  // optional bytes data_1 = 10;
  inline bool has_data_1() const;
  inline void clear_data_1();
  static const int kData1FieldNumber = 10;
  inline const ::std::string& data_1() const;
  inline void set_data_1(const ::std::string& value);
  inline void set_data_1(const char* value);
  inline void set_data_1(const void* value, size_t size);
  inline ::std::string* mutable_data_1();
  inline ::std::string* release_data_1();
  inline void set_allocated_data_1(::std::string* data_1);

  // optional bytes data_2 = 11;
  inline bool has_data_2() const;
  inline void clear_data_2();
  static const int kData2FieldNumber = 11;
  inline const ::std::string& data_2() const;
  inline void set_data_2(const ::std::string& value);
  inline void set_data_2(const char* value);
  inline void set_data_2(const void* value, size_t size);
  inline ::std::string* mutable_data_2();
  inline ::std::string* release_data_2();
  inline void set_allocated_data_2(::std::string* data_2);

  // optional bytes data_3 = 12;
  inline bool has_data_3() const;
  inline void clear_data_3();
  static const int kData3FieldNumber = 12;
  inline const ::std::string& data_3() const;
  inline void set_data_3(const ::std::string& value);
  inline void set_data_3(const char* value);
  inline void set_data_3(const void* value, size_t size);
  inline ::std::string* mutable_data_3();
  inline ::std::string* release_data_3();
  inline void set_allocated_data_3(::std::string* data_3);

  // optional string serverip = 13;
  inline bool has_serverip() const;
  inline void clear_serverip();
  static const int kServeripFieldNumber = 13;
  inline const ::std::string& serverip() const;
  inline void set_serverip(const ::std::string& value);
  inline void set_serverip(const char* value);
  inline void set_serverip(const char* value, size_t size);
  inline ::std::string* mutable_serverip();
  inline ::std::string* release_serverip();
  inline void set_allocated_serverip(::std::string* serverip);

  // optional string clientip = 14;
  inline bool has_clientip() const;
  inline void clear_clientip();
  static const int kClientipFieldNumber = 14;
  inline const ::std::string& clientip() const;
  inline void set_clientip(const ::std::string& value);
  inline void set_clientip(const char* value);
  inline void set_clientip(const char* value, size_t size);
  inline ::std::string* mutable_clientip();
  inline ::std::string* release_clientip();
  inline void set_allocated_clientip(::std::string* clientip);

  // optional string payload = 15;
  inline bool has_payload() const;
  inline void clear_payload();
  static const int kPayloadFieldNumber = 15;
  inline const ::std::string& payload() const;
  inline void set_payload(const ::std::string& value);
  inline void set_payload(const char* value);
  inline void set_payload(const char* value, size_t size);
  inline ::std::string* mutable_payload();
  inline ::std::string* release_payload();
  inline void set_allocated_payload(::std::string* payload);

  // optional string regionfilename = 16;
  inline bool has_regionfilename() const;
  inline void clear_regionfilename();
  static const int kRegionfilenameFieldNumber = 16;
  inline const ::std::string& regionfilename() const;
  inline void set_regionfilename(const ::std::string& value);
  inline void set_regionfilename(const char* value);
  inline void set_regionfilename(const char* value, size_t size);
  inline ::std::string* mutable_regionfilename();
  inline ::std::string* release_regionfilename();
  inline void set_allocated_regionfilename(::std::string* regionfilename);

  // optional bytes regiondata = 17;
  inline bool has_regiondata() const;
  inline void clear_regiondata();
  static const int kRegiondataFieldNumber = 17;
  inline const ::std::string& regiondata() const;
  inline void set_regiondata(const ::std::string& value);
  inline void set_regiondata(const char* value);
  inline void set_regiondata(const void* value, size_t size);
  inline ::std::string* mutable_regiondata();
  inline ::std::string* release_regiondata();
  inline void set_allocated_regiondata(::std::string* regiondata);

  // optional int32 instance = 18;
  inline bool has_instance() const;
  inline void clear_instance();
  static const int kInstanceFieldNumber = 18;
  inline ::google::protobuf::int32 instance() const;
  inline void set_instance(::google::protobuf::int32 value);

  // optional bool storeimage = 19;
  inline bool has_storeimage() const;
  inline void clear_storeimage();
  static const int kStoreimageFieldNumber = 19;
  inline bool storeimage() const;
  inline void set_storeimage(bool value);

  // optional bool storecrop = 20;
  inline bool has_storecrop() const;
  inline void clear_storecrop();
  static const int kStorecropFieldNumber = 20;
  inline bool storecrop() const;
  inline void set_storecrop(bool value);

  // optional string amount = 21;
  inline bool has_amount() const;
  inline void clear_amount();
  static const int kAmountFieldNumber = 21;
  inline const ::std::string& amount() const;
  inline void set_amount(const ::std::string& value);
  inline void set_amount(const char* value);
  inline void set_amount(const char* value, size_t size);
  inline ::std::string* mutable_amount();
  inline ::std::string* release_amount();
  inline void set_allocated_amount(::std::string* amount);

  // optional string filepath = 22;
  inline bool has_filepath() const;
  inline void clear_filepath();
  static const int kFilepathFieldNumber = 22;
  inline const ::std::string& filepath() const;
  inline void set_filepath(const ::std::string& value);
  inline void set_filepath(const char* value);
  inline void set_filepath(const char* value, size_t size);
  inline ::std::string* mutable_filepath();
  inline ::std::string* release_filepath();
  inline void set_allocated_filepath(::std::string* filepath);

  // optional int32 idinstance = 23;
  inline bool has_idinstance() const;
  inline void clear_idinstance();
  static const int kIdinstanceFieldNumber = 23;
  inline ::google::protobuf::int32 idinstance() const;
  inline void set_idinstance(::google::protobuf::int32 value);

  // optional string start = 24;
  inline bool has_start() const;
  inline void clear_start();
  static const int kStartFieldNumber = 24;
  inline const ::std::string& start() const;
  inline void set_start(const ::std::string& value);
  inline void set_start(const char* value);
  inline void set_start(const char* value, size_t size);
  inline ::std::string* mutable_start();
  inline ::std::string* release_start();
  inline void set_allocated_start(::std::string* start);

  // optional string end = 25;
  inline bool has_end() const;
  inline void clear_end();
  static const int kEndFieldNumber = 25;
  inline const ::std::string& end() const;
  inline void set_end(const ::std::string& value);
  inline void set_end(const char* value);
  inline void set_end(const char* value, size_t size);
  inline ::std::string* mutable_end();
  inline ::std::string* release_end();
  inline void set_allocated_end(::std::string* end);

  // @@protoc_insertion_point(class_scope:motion.Message)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_rows();
  inline void clear_has_rows();
  inline void set_has_cols();
  inline void clear_has_cols();
  inline void set_has_typemat();
  inline void clear_has_typemat();
  inline void set_has_size();
  inline void clear_has_size();
  inline void set_has_data_1();
  inline void clear_has_data_1();
  inline void set_has_data_2();
  inline void clear_has_data_2();
  inline void set_has_data_3();
  inline void clear_has_data_3();
  inline void set_has_serverip();
  inline void clear_has_serverip();
  inline void set_has_clientip();
  inline void clear_has_clientip();
  inline void set_has_payload();
  inline void clear_has_payload();
  inline void set_has_regionfilename();
  inline void clear_has_regionfilename();
  inline void set_has_regiondata();
  inline void clear_has_regiondata();
  inline void set_has_instance();
  inline void clear_has_instance();
  inline void set_has_storeimage();
  inline void clear_has_storeimage();
  inline void set_has_storecrop();
  inline void clear_has_storecrop();
  inline void set_has_amount();
  inline void clear_has_amount();
  inline void set_has_filepath();
  inline void clear_has_filepath();
  inline void set_has_idinstance();
  inline void clear_has_idinstance();
  inline void set_has_start();
  inline void clear_has_start();
  inline void set_has_end();
  inline void clear_has_end();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* time_;
  int type_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 rows_;
  ::google::protobuf::int32 cols_;
  ::google::protobuf::int32 typemat_;
  ::std::string* data_1_;
  ::std::string* data_2_;
  ::std::string* data_3_;
  ::std::string* serverip_;
  ::google::protobuf::int32 size_;
  ::google::protobuf::int32 instance_;
  ::std::string* clientip_;
  ::std::string* payload_;
  ::std::string* regionfilename_;
  ::std::string* regiondata_;
  bool storeimage_;
  bool storecrop_;
  ::google::protobuf::int32 idinstance_;
  ::std::string* amount_;
  ::std::string* filepath_;
  ::std::string* start_;
  ::std::string* end_;
  friend void  protobuf_AddDesc_motion_2eproto();
  friend void protobuf_AssignDesc_motion_2eproto();
  friend void protobuf_ShutdownFile_motion_2eproto();

  void InitAsDefaultInstance();
  static Message* default_instance_;
};
// ===================================================================


// ===================================================================

// Message

// required .motion.Message.ActionType type = 1 [default = CONNECT];
inline bool Message::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_type() {
  type_ = 1000;
  clear_has_type();
}
inline ::motion::Message_ActionType Message::type() const {
  // @@protoc_insertion_point(field_get:motion.Message.type)
  return static_cast< ::motion::Message_ActionType >(type_);
}
inline void Message::set_type(::motion::Message_ActionType value) {
  assert(::motion::Message_ActionType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:motion.Message.type)
}

// optional string time = 2;
inline bool Message::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_time() {
  if (time_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    time_->clear();
  }
  clear_has_time();
}
inline const ::std::string& Message::time() const {
  // @@protoc_insertion_point(field_get:motion.Message.time)
  return *time_;
}
inline void Message::set_time(const ::std::string& value) {
  set_has_time();
  if (time_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    time_ = new ::std::string;
  }
  time_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.time)
}
inline void Message::set_time(const char* value) {
  set_has_time();
  if (time_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    time_ = new ::std::string;
  }
  time_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.time)
}
inline void Message::set_time(const char* value, size_t size) {
  set_has_time();
  if (time_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    time_ = new ::std::string;
  }
  time_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.time)
}
inline ::std::string* Message::mutable_time() {
  set_has_time();
  if (time_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    time_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.time)
  return time_;
}
inline ::std::string* Message::release_time() {
  clear_has_time();
  if (time_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = time_;
    time_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_time(::std::string* time) {
  if (time_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete time_;
  }
  if (time) {
    set_has_time();
    time_ = time;
  } else {
    clear_has_time();
    time_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.time)
}

// optional int32 width = 3;
inline bool Message::has_width() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Message::set_has_width() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Message::clear_has_width() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Message::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 Message::width() const {
  // @@protoc_insertion_point(field_get:motion.Message.width)
  return width_;
}
inline void Message::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:motion.Message.width)
}

// optional int32 height = 4;
inline bool Message::has_height() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Message::set_has_height() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Message::clear_has_height() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Message::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline ::google::protobuf::int32 Message::height() const {
  // @@protoc_insertion_point(field_get:motion.Message.height)
  return height_;
}
inline void Message::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:motion.Message.height)
}

// optional int32 rows = 5;
inline bool Message::has_rows() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Message::set_has_rows() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Message::clear_has_rows() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Message::clear_rows() {
  rows_ = 0;
  clear_has_rows();
}
inline ::google::protobuf::int32 Message::rows() const {
  // @@protoc_insertion_point(field_get:motion.Message.rows)
  return rows_;
}
inline void Message::set_rows(::google::protobuf::int32 value) {
  set_has_rows();
  rows_ = value;
  // @@protoc_insertion_point(field_set:motion.Message.rows)
}

// optional int32 cols = 6;
inline bool Message::has_cols() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Message::set_has_cols() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Message::clear_has_cols() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Message::clear_cols() {
  cols_ = 0;
  clear_has_cols();
}
inline ::google::protobuf::int32 Message::cols() const {
  // @@protoc_insertion_point(field_get:motion.Message.cols)
  return cols_;
}
inline void Message::set_cols(::google::protobuf::int32 value) {
  set_has_cols();
  cols_ = value;
  // @@protoc_insertion_point(field_set:motion.Message.cols)
}

// optional int32 typemat = 7;
inline bool Message::has_typemat() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Message::set_has_typemat() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Message::clear_has_typemat() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Message::clear_typemat() {
  typemat_ = 0;
  clear_has_typemat();
}
inline ::google::protobuf::int32 Message::typemat() const {
  // @@protoc_insertion_point(field_get:motion.Message.typemat)
  return typemat_;
}
inline void Message::set_typemat(::google::protobuf::int32 value) {
  set_has_typemat();
  typemat_ = value;
  // @@protoc_insertion_point(field_set:motion.Message.typemat)
}

// optional int32 size = 8;
inline bool Message::has_size() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Message::set_has_size() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Message::clear_has_size() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Message::clear_size() {
  size_ = 0;
  clear_has_size();
}
inline ::google::protobuf::int32 Message::size() const {
  // @@protoc_insertion_point(field_get:motion.Message.size)
  return size_;
}
inline void Message::set_size(::google::protobuf::int32 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:motion.Message.size)
}

// optional bytes data_1 = 10;
inline bool Message::has_data_1() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Message::set_has_data_1() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Message::clear_has_data_1() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Message::clear_data_1() {
  if (data_1_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_1_->clear();
  }
  clear_has_data_1();
}
inline const ::std::string& Message::data_1() const {
  // @@protoc_insertion_point(field_get:motion.Message.data_1)
  return *data_1_;
}
inline void Message::set_data_1(const ::std::string& value) {
  set_has_data_1();
  if (data_1_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_1_ = new ::std::string;
  }
  data_1_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.data_1)
}
inline void Message::set_data_1(const char* value) {
  set_has_data_1();
  if (data_1_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_1_ = new ::std::string;
  }
  data_1_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.data_1)
}
inline void Message::set_data_1(const void* value, size_t size) {
  set_has_data_1();
  if (data_1_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_1_ = new ::std::string;
  }
  data_1_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.data_1)
}
inline ::std::string* Message::mutable_data_1() {
  set_has_data_1();
  if (data_1_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_1_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.data_1)
  return data_1_;
}
inline ::std::string* Message::release_data_1() {
  clear_has_data_1();
  if (data_1_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_1_;
    data_1_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_data_1(::std::string* data_1) {
  if (data_1_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_1_;
  }
  if (data_1) {
    set_has_data_1();
    data_1_ = data_1;
  } else {
    clear_has_data_1();
    data_1_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.data_1)
}

// optional bytes data_2 = 11;
inline bool Message::has_data_2() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Message::set_has_data_2() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Message::clear_has_data_2() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Message::clear_data_2() {
  if (data_2_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_2_->clear();
  }
  clear_has_data_2();
}
inline const ::std::string& Message::data_2() const {
  // @@protoc_insertion_point(field_get:motion.Message.data_2)
  return *data_2_;
}
inline void Message::set_data_2(const ::std::string& value) {
  set_has_data_2();
  if (data_2_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_2_ = new ::std::string;
  }
  data_2_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.data_2)
}
inline void Message::set_data_2(const char* value) {
  set_has_data_2();
  if (data_2_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_2_ = new ::std::string;
  }
  data_2_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.data_2)
}
inline void Message::set_data_2(const void* value, size_t size) {
  set_has_data_2();
  if (data_2_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_2_ = new ::std::string;
  }
  data_2_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.data_2)
}
inline ::std::string* Message::mutable_data_2() {
  set_has_data_2();
  if (data_2_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_2_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.data_2)
  return data_2_;
}
inline ::std::string* Message::release_data_2() {
  clear_has_data_2();
  if (data_2_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_2_;
    data_2_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_data_2(::std::string* data_2) {
  if (data_2_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_2_;
  }
  if (data_2) {
    set_has_data_2();
    data_2_ = data_2;
  } else {
    clear_has_data_2();
    data_2_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.data_2)
}

// optional bytes data_3 = 12;
inline bool Message::has_data_3() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Message::set_has_data_3() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Message::clear_has_data_3() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Message::clear_data_3() {
  if (data_3_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_3_->clear();
  }
  clear_has_data_3();
}
inline const ::std::string& Message::data_3() const {
  // @@protoc_insertion_point(field_get:motion.Message.data_3)
  return *data_3_;
}
inline void Message::set_data_3(const ::std::string& value) {
  set_has_data_3();
  if (data_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_3_ = new ::std::string;
  }
  data_3_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.data_3)
}
inline void Message::set_data_3(const char* value) {
  set_has_data_3();
  if (data_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_3_ = new ::std::string;
  }
  data_3_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.data_3)
}
inline void Message::set_data_3(const void* value, size_t size) {
  set_has_data_3();
  if (data_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_3_ = new ::std::string;
  }
  data_3_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.data_3)
}
inline ::std::string* Message::mutable_data_3() {
  set_has_data_3();
  if (data_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_3_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.data_3)
  return data_3_;
}
inline ::std::string* Message::release_data_3() {
  clear_has_data_3();
  if (data_3_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_3_;
    data_3_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_data_3(::std::string* data_3) {
  if (data_3_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_3_;
  }
  if (data_3) {
    set_has_data_3();
    data_3_ = data_3;
  } else {
    clear_has_data_3();
    data_3_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.data_3)
}

// optional string serverip = 13;
inline bool Message::has_serverip() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Message::set_has_serverip() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Message::clear_has_serverip() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Message::clear_serverip() {
  if (serverip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    serverip_->clear();
  }
  clear_has_serverip();
}
inline const ::std::string& Message::serverip() const {
  // @@protoc_insertion_point(field_get:motion.Message.serverip)
  return *serverip_;
}
inline void Message::set_serverip(const ::std::string& value) {
  set_has_serverip();
  if (serverip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    serverip_ = new ::std::string;
  }
  serverip_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.serverip)
}
inline void Message::set_serverip(const char* value) {
  set_has_serverip();
  if (serverip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    serverip_ = new ::std::string;
  }
  serverip_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.serverip)
}
inline void Message::set_serverip(const char* value, size_t size) {
  set_has_serverip();
  if (serverip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    serverip_ = new ::std::string;
  }
  serverip_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.serverip)
}
inline ::std::string* Message::mutable_serverip() {
  set_has_serverip();
  if (serverip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    serverip_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.serverip)
  return serverip_;
}
inline ::std::string* Message::release_serverip() {
  clear_has_serverip();
  if (serverip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = serverip_;
    serverip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_serverip(::std::string* serverip) {
  if (serverip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete serverip_;
  }
  if (serverip) {
    set_has_serverip();
    serverip_ = serverip;
  } else {
    clear_has_serverip();
    serverip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.serverip)
}

// optional string clientip = 14;
inline bool Message::has_clientip() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void Message::set_has_clientip() {
  _has_bits_[0] |= 0x00001000u;
}
inline void Message::clear_has_clientip() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void Message::clear_clientip() {
  if (clientip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    clientip_->clear();
  }
  clear_has_clientip();
}
inline const ::std::string& Message::clientip() const {
  // @@protoc_insertion_point(field_get:motion.Message.clientip)
  return *clientip_;
}
inline void Message::set_clientip(const ::std::string& value) {
  set_has_clientip();
  if (clientip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    clientip_ = new ::std::string;
  }
  clientip_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.clientip)
}
inline void Message::set_clientip(const char* value) {
  set_has_clientip();
  if (clientip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    clientip_ = new ::std::string;
  }
  clientip_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.clientip)
}
inline void Message::set_clientip(const char* value, size_t size) {
  set_has_clientip();
  if (clientip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    clientip_ = new ::std::string;
  }
  clientip_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.clientip)
}
inline ::std::string* Message::mutable_clientip() {
  set_has_clientip();
  if (clientip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    clientip_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.clientip)
  return clientip_;
}
inline ::std::string* Message::release_clientip() {
  clear_has_clientip();
  if (clientip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = clientip_;
    clientip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_clientip(::std::string* clientip) {
  if (clientip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete clientip_;
  }
  if (clientip) {
    set_has_clientip();
    clientip_ = clientip;
  } else {
    clear_has_clientip();
    clientip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.clientip)
}

// optional string payload = 15;
inline bool Message::has_payload() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void Message::set_has_payload() {
  _has_bits_[0] |= 0x00002000u;
}
inline void Message::clear_has_payload() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void Message::clear_payload() {
  if (payload_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    payload_->clear();
  }
  clear_has_payload();
}
inline const ::std::string& Message::payload() const {
  // @@protoc_insertion_point(field_get:motion.Message.payload)
  return *payload_;
}
inline void Message::set_payload(const ::std::string& value) {
  set_has_payload();
  if (payload_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    payload_ = new ::std::string;
  }
  payload_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.payload)
}
inline void Message::set_payload(const char* value) {
  set_has_payload();
  if (payload_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    payload_ = new ::std::string;
  }
  payload_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.payload)
}
inline void Message::set_payload(const char* value, size_t size) {
  set_has_payload();
  if (payload_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    payload_ = new ::std::string;
  }
  payload_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.payload)
}
inline ::std::string* Message::mutable_payload() {
  set_has_payload();
  if (payload_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    payload_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.payload)
  return payload_;
}
inline ::std::string* Message::release_payload() {
  clear_has_payload();
  if (payload_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = payload_;
    payload_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_payload(::std::string* payload) {
  if (payload_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete payload_;
  }
  if (payload) {
    set_has_payload();
    payload_ = payload;
  } else {
    clear_has_payload();
    payload_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.payload)
}

// optional string regionfilename = 16;
inline bool Message::has_regionfilename() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void Message::set_has_regionfilename() {
  _has_bits_[0] |= 0x00004000u;
}
inline void Message::clear_has_regionfilename() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void Message::clear_regionfilename() {
  if (regionfilename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    regionfilename_->clear();
  }
  clear_has_regionfilename();
}
inline const ::std::string& Message::regionfilename() const {
  // @@protoc_insertion_point(field_get:motion.Message.regionfilename)
  return *regionfilename_;
}
inline void Message::set_regionfilename(const ::std::string& value) {
  set_has_regionfilename();
  if (regionfilename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    regionfilename_ = new ::std::string;
  }
  regionfilename_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.regionfilename)
}
inline void Message::set_regionfilename(const char* value) {
  set_has_regionfilename();
  if (regionfilename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    regionfilename_ = new ::std::string;
  }
  regionfilename_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.regionfilename)
}
inline void Message::set_regionfilename(const char* value, size_t size) {
  set_has_regionfilename();
  if (regionfilename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    regionfilename_ = new ::std::string;
  }
  regionfilename_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.regionfilename)
}
inline ::std::string* Message::mutable_regionfilename() {
  set_has_regionfilename();
  if (regionfilename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    regionfilename_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.regionfilename)
  return regionfilename_;
}
inline ::std::string* Message::release_regionfilename() {
  clear_has_regionfilename();
  if (regionfilename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = regionfilename_;
    regionfilename_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_regionfilename(::std::string* regionfilename) {
  if (regionfilename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete regionfilename_;
  }
  if (regionfilename) {
    set_has_regionfilename();
    regionfilename_ = regionfilename;
  } else {
    clear_has_regionfilename();
    regionfilename_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.regionfilename)
}

// optional bytes regiondata = 17;
inline bool Message::has_regiondata() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void Message::set_has_regiondata() {
  _has_bits_[0] |= 0x00008000u;
}
inline void Message::clear_has_regiondata() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void Message::clear_regiondata() {
  if (regiondata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    regiondata_->clear();
  }
  clear_has_regiondata();
}
inline const ::std::string& Message::regiondata() const {
  // @@protoc_insertion_point(field_get:motion.Message.regiondata)
  return *regiondata_;
}
inline void Message::set_regiondata(const ::std::string& value) {
  set_has_regiondata();
  if (regiondata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    regiondata_ = new ::std::string;
  }
  regiondata_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.regiondata)
}
inline void Message::set_regiondata(const char* value) {
  set_has_regiondata();
  if (regiondata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    regiondata_ = new ::std::string;
  }
  regiondata_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.regiondata)
}
inline void Message::set_regiondata(const void* value, size_t size) {
  set_has_regiondata();
  if (regiondata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    regiondata_ = new ::std::string;
  }
  regiondata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.regiondata)
}
inline ::std::string* Message::mutable_regiondata() {
  set_has_regiondata();
  if (regiondata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    regiondata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.regiondata)
  return regiondata_;
}
inline ::std::string* Message::release_regiondata() {
  clear_has_regiondata();
  if (regiondata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = regiondata_;
    regiondata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_regiondata(::std::string* regiondata) {
  if (regiondata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete regiondata_;
  }
  if (regiondata) {
    set_has_regiondata();
    regiondata_ = regiondata;
  } else {
    clear_has_regiondata();
    regiondata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.regiondata)
}

// optional int32 instance = 18;
inline bool Message::has_instance() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void Message::set_has_instance() {
  _has_bits_[0] |= 0x00010000u;
}
inline void Message::clear_has_instance() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void Message::clear_instance() {
  instance_ = 0;
  clear_has_instance();
}
inline ::google::protobuf::int32 Message::instance() const {
  // @@protoc_insertion_point(field_get:motion.Message.instance)
  return instance_;
}
inline void Message::set_instance(::google::protobuf::int32 value) {
  set_has_instance();
  instance_ = value;
  // @@protoc_insertion_point(field_set:motion.Message.instance)
}

// optional bool storeimage = 19;
inline bool Message::has_storeimage() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
inline void Message::set_has_storeimage() {
  _has_bits_[0] |= 0x00020000u;
}
inline void Message::clear_has_storeimage() {
  _has_bits_[0] &= ~0x00020000u;
}
inline void Message::clear_storeimage() {
  storeimage_ = false;
  clear_has_storeimage();
}
inline bool Message::storeimage() const {
  // @@protoc_insertion_point(field_get:motion.Message.storeimage)
  return storeimage_;
}
inline void Message::set_storeimage(bool value) {
  set_has_storeimage();
  storeimage_ = value;
  // @@protoc_insertion_point(field_set:motion.Message.storeimage)
}

// optional bool storecrop = 20;
inline bool Message::has_storecrop() const {
  return (_has_bits_[0] & 0x00040000u) != 0;
}
inline void Message::set_has_storecrop() {
  _has_bits_[0] |= 0x00040000u;
}
inline void Message::clear_has_storecrop() {
  _has_bits_[0] &= ~0x00040000u;
}
inline void Message::clear_storecrop() {
  storecrop_ = false;
  clear_has_storecrop();
}
inline bool Message::storecrop() const {
  // @@protoc_insertion_point(field_get:motion.Message.storecrop)
  return storecrop_;
}
inline void Message::set_storecrop(bool value) {
  set_has_storecrop();
  storecrop_ = value;
  // @@protoc_insertion_point(field_set:motion.Message.storecrop)
}

// optional string amount = 21;
inline bool Message::has_amount() const {
  return (_has_bits_[0] & 0x00080000u) != 0;
}
inline void Message::set_has_amount() {
  _has_bits_[0] |= 0x00080000u;
}
inline void Message::clear_has_amount() {
  _has_bits_[0] &= ~0x00080000u;
}
inline void Message::clear_amount() {
  if (amount_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    amount_->clear();
  }
  clear_has_amount();
}
inline const ::std::string& Message::amount() const {
  // @@protoc_insertion_point(field_get:motion.Message.amount)
  return *amount_;
}
inline void Message::set_amount(const ::std::string& value) {
  set_has_amount();
  if (amount_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    amount_ = new ::std::string;
  }
  amount_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.amount)
}
inline void Message::set_amount(const char* value) {
  set_has_amount();
  if (amount_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    amount_ = new ::std::string;
  }
  amount_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.amount)
}
inline void Message::set_amount(const char* value, size_t size) {
  set_has_amount();
  if (amount_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    amount_ = new ::std::string;
  }
  amount_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.amount)
}
inline ::std::string* Message::mutable_amount() {
  set_has_amount();
  if (amount_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    amount_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.amount)
  return amount_;
}
inline ::std::string* Message::release_amount() {
  clear_has_amount();
  if (amount_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = amount_;
    amount_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_amount(::std::string* amount) {
  if (amount_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete amount_;
  }
  if (amount) {
    set_has_amount();
    amount_ = amount;
  } else {
    clear_has_amount();
    amount_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.amount)
}

// optional string filepath = 22;
inline bool Message::has_filepath() const {
  return (_has_bits_[0] & 0x00100000u) != 0;
}
inline void Message::set_has_filepath() {
  _has_bits_[0] |= 0x00100000u;
}
inline void Message::clear_has_filepath() {
  _has_bits_[0] &= ~0x00100000u;
}
inline void Message::clear_filepath() {
  if (filepath_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filepath_->clear();
  }
  clear_has_filepath();
}
inline const ::std::string& Message::filepath() const {
  // @@protoc_insertion_point(field_get:motion.Message.filepath)
  return *filepath_;
}
inline void Message::set_filepath(const ::std::string& value) {
  set_has_filepath();
  if (filepath_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filepath_ = new ::std::string;
  }
  filepath_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.filepath)
}
inline void Message::set_filepath(const char* value) {
  set_has_filepath();
  if (filepath_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filepath_ = new ::std::string;
  }
  filepath_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.filepath)
}
inline void Message::set_filepath(const char* value, size_t size) {
  set_has_filepath();
  if (filepath_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filepath_ = new ::std::string;
  }
  filepath_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.filepath)
}
inline ::std::string* Message::mutable_filepath() {
  set_has_filepath();
  if (filepath_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filepath_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.filepath)
  return filepath_;
}
inline ::std::string* Message::release_filepath() {
  clear_has_filepath();
  if (filepath_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = filepath_;
    filepath_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_filepath(::std::string* filepath) {
  if (filepath_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete filepath_;
  }
  if (filepath) {
    set_has_filepath();
    filepath_ = filepath;
  } else {
    clear_has_filepath();
    filepath_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.filepath)
}

// optional int32 idinstance = 23;
inline bool Message::has_idinstance() const {
  return (_has_bits_[0] & 0x00200000u) != 0;
}
inline void Message::set_has_idinstance() {
  _has_bits_[0] |= 0x00200000u;
}
inline void Message::clear_has_idinstance() {
  _has_bits_[0] &= ~0x00200000u;
}
inline void Message::clear_idinstance() {
  idinstance_ = 0;
  clear_has_idinstance();
}
inline ::google::protobuf::int32 Message::idinstance() const {
  // @@protoc_insertion_point(field_get:motion.Message.idinstance)
  return idinstance_;
}
inline void Message::set_idinstance(::google::protobuf::int32 value) {
  set_has_idinstance();
  idinstance_ = value;
  // @@protoc_insertion_point(field_set:motion.Message.idinstance)
}

// optional string start = 24;
inline bool Message::has_start() const {
  return (_has_bits_[0] & 0x00400000u) != 0;
}
inline void Message::set_has_start() {
  _has_bits_[0] |= 0x00400000u;
}
inline void Message::clear_has_start() {
  _has_bits_[0] &= ~0x00400000u;
}
inline void Message::clear_start() {
  if (start_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_->clear();
  }
  clear_has_start();
}
inline const ::std::string& Message::start() const {
  // @@protoc_insertion_point(field_get:motion.Message.start)
  return *start_;
}
inline void Message::set_start(const ::std::string& value) {
  set_has_start();
  if (start_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_ = new ::std::string;
  }
  start_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.start)
}
inline void Message::set_start(const char* value) {
  set_has_start();
  if (start_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_ = new ::std::string;
  }
  start_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.start)
}
inline void Message::set_start(const char* value, size_t size) {
  set_has_start();
  if (start_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_ = new ::std::string;
  }
  start_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.start)
}
inline ::std::string* Message::mutable_start() {
  set_has_start();
  if (start_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.start)
  return start_;
}
inline ::std::string* Message::release_start() {
  clear_has_start();
  if (start_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = start_;
    start_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_start(::std::string* start) {
  if (start_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete start_;
  }
  if (start) {
    set_has_start();
    start_ = start;
  } else {
    clear_has_start();
    start_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.start)
}

// optional string end = 25;
inline bool Message::has_end() const {
  return (_has_bits_[0] & 0x00800000u) != 0;
}
inline void Message::set_has_end() {
  _has_bits_[0] |= 0x00800000u;
}
inline void Message::clear_has_end() {
  _has_bits_[0] &= ~0x00800000u;
}
inline void Message::clear_end() {
  if (end_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_->clear();
  }
  clear_has_end();
}
inline const ::std::string& Message::end() const {
  // @@protoc_insertion_point(field_get:motion.Message.end)
  return *end_;
}
inline void Message::set_end(const ::std::string& value) {
  set_has_end();
  if (end_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_ = new ::std::string;
  }
  end_->assign(value);
  // @@protoc_insertion_point(field_set:motion.Message.end)
}
inline void Message::set_end(const char* value) {
  set_has_end();
  if (end_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_ = new ::std::string;
  }
  end_->assign(value);
  // @@protoc_insertion_point(field_set_char:motion.Message.end)
}
inline void Message::set_end(const char* value, size_t size) {
  set_has_end();
  if (end_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_ = new ::std::string;
  }
  end_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:motion.Message.end)
}
inline ::std::string* Message::mutable_end() {
  set_has_end();
  if (end_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:motion.Message.end)
  return end_;
}
inline ::std::string* Message::release_end() {
  clear_has_end();
  if (end_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = end_;
    end_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_end(::std::string* end) {
  if (end_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete end_;
  }
  if (end) {
    set_has_end();
    end_ = end;
  } else {
    clear_has_end();
    end_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:motion.Message.end)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace motion

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::motion::Message_ActionType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::motion::Message_ActionType>() {
  return ::motion::Message_ActionType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_motion_2eproto__INCLUDED
